version: '3.3'


services:
    app:
        build: './node-app'
        container_name: 'app'
    proxy:
        build: './proxy'
        container_name: 'proxy'
        ports:
            - '80:80'
        links:
            - app
